### ISSUE TITLE
Playlist Search Function not working

### ISSUE THREAD

**Issue by dmsanderswdet** [wdetdigital/wdet-conversion#149] opened 2022-03-15 17:51 UTC
The playlist search function has never worked property I’ve tested using every filed by searching for titles that I know have aired and they don’t come up in the search. It’s been basically worthless. E-mail from JMosier

**Comment by artlogic** [comment] 2022-03-15 19:27
@dmsanderswdet please assign this to a person and a milestone

**Comment by artlogic** [comment] 2022-03-15 19:32
> I would have to leave that up to you and Tony. Tony asked me to put it in Github after he received the email. I don't believe I'm in a position to determine the level of importance or to assign it to anyone.

OK - we'll leave these unassigned until we meet next or until they can be triaged.

**Comment by wdet30** [comment] 2022-04-06 14:31
This is not an issue. The user was not able to reproduce the issue.

**Closed by wdet30** 2022-04-06 14:31 UTC
Labels: bug
